# Generated by Django 4.1 on 2022-08-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='offer',
            field=models.CharField(default=80, max_length=30),
            preserve_default=False,
        ),
    ]
