# Generated by Django 4.1 on 2022-08-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='in_stock',
            field=models.BooleanField(default=1, verbose_name='Stock'),
            preserve_default=False,
        ),
    ]
