# Generated by Django 4.1 on 2022-08-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='in_stock',
            field=models.IntegerField(),
        ),
    ]
