# Generated by Django 4.1 on 2022-08-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_category_alter_producto_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clasification',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=1),
            preserve_default=False,
        ),
    ]
