# Generated by Django 4.1 on 2022-08-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_producto_code_alter_producto_clasification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='clasification',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/img/productos'),
        ),
    ]
