# Generated by Django 4.1 on 2022-08-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_alter_producto_code_alter_producto_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='in_stock',
            field=models.IntegerField(default=1),
        ),
    ]
