# Generated by Django 4.1 on 2022-08-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
