# Generated by Django 4.1 on 2022-08-16 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_category_company_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='category',
        ),
    ]
