# Generated by Django 4.1 on 2022-08-17 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.currency'),
        ),
    ]
