# Generated by Django 4.1 on 2022-08-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
